<?php

/**
 * Headless Matomo installation for the development environment.
 * Runs inside the "matomo" container: php /var/www/html/plugins/AmazonSES/.docker/install.php
 *
 * Mirrors the steps of plugins/Installation/Controller.php (tables, super user, first website).
 */

$root = '/var/www/html';
$configFile = "$root/config/config.ini.php";

$env = function (string $name, string $default = ''): string {
    $value = getenv($name);
    return $value === false || $value === '' ? $default : $value;
};

$db = [
    'host' => $env('MATOMO_DATABASE_HOST', 'db'),
    'username' => $env('MATOMO_DATABASE_USERNAME', 'matomo'),
    'password' => $env('MATOMO_DATABASE_PASSWORD', 'matomo'),
    'dbname' => $env('MATOMO_DATABASE_DBNAME', 'matomo'),
    'tables_prefix' => $env('MATOMO_DATABASE_TABLES_PREFIX', 'matomo_'),
];
$admin = [
    'login' => $env('MATOMO_ADMIN_LOGIN', 'admin'),
    'password' => $env('MATOMO_ADMIN_PASSWORD', 'admin123'),
    'email' => $env('MATOMO_ADMIN_EMAIL', 'admin@example.com'),
];
$siteUrl = $env('MATOMO_SITE_URL', 'http://localhost:8080');

// 1. wait for the database
$dsn = sprintf('mysql:host=%s;dbname=%s', $db['host'], $db['dbname']);
for ($i = 0; ; $i++) {
    try {
        $pdo = new PDO($dsn, $db['username'], $db['password']);
        break;
    } catch (PDOException $e) {
        if ($i > 60) {
            fwrite(STDERR, "Database not reachable: {$e->getMessage()}\n");
            exit(1);
        }
        sleep(1);
    }
}

$tables = $pdo->query("SHOW TABLES LIKE '{$db['tables_prefix']}option'")->fetchAll();
if (is_file($configFile) && count($tables) > 0) {
    echo "Matomo is already installed, nothing to do.\n";
    exit(0);
}

// 2. config file
$host = parse_url($siteUrl, PHP_URL_HOST) . (parse_url($siteUrl, PHP_URL_PORT) ? ':' . parse_url($siteUrl, PHP_URL_PORT) : '');
$ini = <<<INI
; <?php exit; ?> DO NOT REMOVE THIS LINE
; generated by .docker/install.php
[database]
host = "{$db['host']}"
username = "{$db['username']}"
password = "{$db['password']}"
dbname = "{$db['dbname']}"
tables_prefix = "{$db['tables_prefix']}"
adapter = "PDO\MYSQL"
charset = "utf8mb4"
collation = "utf8mb4_general_ci"

[General]
salt = "%s"
trusted_hosts[] = "$host"
trusted_hosts[] = "localhost"
enable_update_communication = 0
noreply_email_address = "noreply@example.com"
noreply_email_name = "Matomo (dev)"

[mail]
defaultHostnameIfEmpty = "example.com"

INI;
file_put_contents($configFile, sprintf($ini, bin2hex(random_bytes(16))));
echo "Wrote $configFile\n";

// 3. bootstrap Matomo
define('PIWIK_INCLUDE_PATH', $root);
define('PIWIK_USER_PATH', $root);
define('PIWIK_DOCUMENT_ROOT', $root);
define('PIWIK_ENABLE_DISPATCH', false);
define('PIWIK_ENABLE_ERROR_HANDLER', false);
define('PIWIK_ENABLE_SESSION_START', false);
require_once $root . '/core/bootstrap.php';

$environment = new \Piwik\Application\Environment('cli');
$environment->init();

use Piwik\Access;
use Piwik\DbHelper;
use Piwik\Plugin\Manager;
use Piwik\Plugins\SitesManager\API as SitesManagerApi;
use Piwik\Plugins\UsersManager\API as UsersManagerApi;
use Piwik\Plugins\UsersManager\UserUpdater;
use Piwik\Updater;
use Piwik\Version;

Access::doAsSuperUser(function () use ($admin, $siteUrl) {
    DbHelper::checkDatabaseVersion();
    DbHelper::createTables();
    DbHelper::createAnonymousUser();
    DbHelper::recordInstallVersion();

    $updater = new Updater();
    $components = $updater->getComponentUpdates();
    if (!empty($components)) {
        $updater->updateComponents($components);
    }
    Updater::recordComponentSuccessfullyUpdated('core', Version::VERSION);

    Manager::getInstance()->loadActivatedPlugins();
    Manager::getInstance()->installLoadedPlugins();
    echo "Tables created, Matomo " . Version::VERSION . "\n";

    UsersManagerApi::getInstance()->addUser($admin['login'], $admin['password'], $admin['email']);
    (new UserUpdater())->setSuperUserAccessWithoutCurrentPassword($admin['login'], true);
    echo "Super user {$admin['login']} created\n";

    $idSite = SitesManagerApi::getInstance()->addSite('Demo site', [$siteUrl]);
    echo "Website created (idSite=$idSite)\n";
});
